Milestone 3
Audrey-Ella-xo/calculator pull request #4
Opened 2021-01-13 15:05 UTC by Audrey-Ella-xo

Hi Reviewer,

In this milestone, I did the following;
   - Added basic styling to the calculator.
   
I am looking forward to your favourable and swift feedback.
Warm regards

2021-01-13 15:52 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @Audrey-Ella-xo :hand: 
Since the version of your Calculator project, it's 1.0 and not 1.1, we need to apply the provided style to your project. We need to follow these requirements [here](https://microverse.pathwright.com/library/react-redux-v10/188148/path/step/107676524/) to style your project.

- [x] We need to use the provided style [here](https://github.com/microverseinc/project-react-calculator/blob/master/images/calculator.png)
![Screenshot from 2021-01-13 12-41-52](https://user-images.githubusercontent.com/30977845/104474395-bbdcc900-559c-11eb-89b1-5e70c1222205.png)

- [x] The result should be provided in white and bold text.
![Screenshot from 2021-01-13 12-43-26](https://user-images.githubusercontent.com/30977845/104474662-00686480-559d-11eb-8bb1-157899424906.png)

- [x] Each row from the button panel should have 100px
![Screenshot from 2021-01-13 12-45-00](https://user-images.githubusercontent.com/30977845/104474843-2f7ed600-559d-11eb-934a-61ba5896d971.png)

Feel free to message me in Slack if you have any questions :smile:.
Happy coding :computer: 
**Sergio Torres**

2021-01-13 15:52 UTC, Torres-ssf commented on src/components/Button.js
>        {name}
- [ ] Button component should accept `color` and `wide` as incoming props.
![Screenshot from 2021-01-13 12-48-25](https://user-images.githubusercontent.com/30977845/104475256-a5833d00-559d-11eb-9f2f-dc58f58beb7e.png)

- [ ] Default `color` for the button should be orange.
![Screenshot from 2021-01-13 12-49-46](https://user-images.githubusercontent.com/30977845/104475413-d5cadb80-559d-11eb-8a3e-f97dfb659e27.png)

- [ ] `wide` is boolean, true means that button take 50% of space (used for `0` button)
![Screenshot from 2021-01-13 12-50-39](https://user-images.githubusercontent.com/30977845/104475507-f430d700-559d-11eb-9825-d07f8b16a1a5.png)

2021-01-14 00:29 UTC, shloch approved these changes
## Hello @Audrey-Ella-xo 
Based on the corrections you made in relation to the former review, this milestone is given a thumbs up. The outcome is good.
![calc](https://user-images.githubusercontent.com/40712459/104528562-ec0d8180-5607-11eb-87bc-8244e41b5c2e.gif)

Happy coding

2021-01-14 00:29 UTC, shloch commented on src/components/Button.js
> +};
Great job working on this component, you understood the TSE's request

2021-01-14 06:54 UTC, merged